'''
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
'''


def euler2():

    prevfirst = 1
    prevsecond = 2
    evensum = 2
    sum = 0
    while sum < 4000000:
        sum = prevfirst + prevsecond
        if sum % 2 == 0:
            evensum = evensum + sum

        prevfirst = prevsecond
        prevsecond = sum

    #print("Sum of multiples of 3 and 5 is : %d" % sum_of_multiples_3_5)
    #print("List of  is : %s" % multiples_of_3_5)
    print(f'sum of fibonacci even numbers  {evensum}')


if __name__ == "__main__":
    euler2()



